import React from 'react'
import s from './InitialAbout.module.css'
import { motion } from 'framer-motion'

const InitialAbout = () => {
    return (
        <motion.div className={s.OutterDIV}
            initial={{ y: 200, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.5, stiffness: 0, duration: 0.8 }}
            viewport={{ once: true }}>
            <motion.h1>
                Sobre Nosotros</motion.h1>
                <div className={s.TextDIV}>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio perferendis quam aspernatur nihil quis. Dignissimos, earum esse quas accusamus dolorum quaerat maiores debitis saepe itaque temporibus id quam aliquid eius iste rerum quasi, beatae repellat ipsam reprehenderit harum iusto inventore cum minima. Minima, velit ad quo illum ut debitis dolores rerum et est quaerat nemo, nihil, incidunt ipsum! Exercitationem est, molestias nobis temporibus ratione laboriosam a expedita veniam officia! Dolorum beatae in laborum, nobis cumque modi magni suscipit optio doloribus esse consectetur quae atque eligendi possimus fugiat, ratione eveniet perspiciatis nemo exercitationem magnam commodi saepe. Delectus, consequatur numquam itaque ab quas temporibus rem quos doloribus illo beatae iusto est nulla illum, magnam animi repudiandae porro corporis expedita fugiat reprehenderit! Error odio iusto saepe expedita sunt corrupti unde ea sequi, provident at voluptates incidunt nesciunt aliquam id est earum tempora soluta animi optio quos voluptatem? Quis voluptas sed sunt autem animi cupiditate voluptatibus modi possimus ad, suscipit pariatur, numquam non eaque tenetur sapiente hic nemo facilis quidem illo velit, ex illum minima. Quidem, atque corrupti ipsam autem, excepturi libero, eaque officia vitae repellendus cumque enim odio ipsa dicta recusandae quaerat culpa temporibus at. Fugiat nisi tempora dolores suscipit quam. Quasi cumque modi soluta libero eaque beatae rem quidem distinctio cum officia labore, nesciunt dolorum voluptas amet saepe esse minima quae velit tempora iste sit quibusdam! Dicta est qui iste minima vero quam a dolorem quibusdam nulla, ab ex itaque repudiandae neque tenetur adipisci dolores, praesentium quaerat sed magnam nesciunt vel recusandae?
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio veniam minima quibusdam voluptas perspiciatis eius possimus numquam hic, ipsum veritatis? Error autem obcaecati voluptates omnis, sequi, adipisci eveniet facilis numquam, ipsa magnam vel quidem fugiat voluptate repellat ullam! Accusantium modi deleniti recusandae minima, dicta labore aspernatur numquam aliquam illum! Amet illo cupiditate quia veritatis aliquid, voluptatibus fuga sunt excepturi omnis cum perferendis est dignissimos doloribus consectetur repellendus laudantium eligendi repellat? Suscipit natus, error et qui odio inventore eveniet consectetur repellat nemo voluptatum necessitatibus voluptatem corrupti dignissimos voluptate, vitae unde! Accusantium dicta magni fugiat dolore vitae molestiae corrupti nobis facere atque, mollitia, est quod enim optio perspiciatis, adipisci totam quisquam laborum rem aperiam iusto dolorem maxime. Laborum saepe blanditiis harum, corrupti voluptatibus culpa ullam et eum ut doloribus id eveniet. Quo voluptate earum maiores veritatis quaerat dolore alias iste minima placeat sint ipsa, repellendus suscipit sed vitae reprehenderit quia nisi itaque.
                    </p>
                    <p>
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam molestiae, quibusdam sunt itaque adipisci nemo optio in. Perspiciatis ullam repellendus laboriosam. Dignissimos voluptatum cumque voluptatem, debitis est aliquam neque officia accusamus, molestias ipsam, provident nostrum facere voluptate cupiditate fuga. Ex, nemo voluptatem quis beatae aliquam mollitia dolores laboriosam enim officiis eos! Distinctio porro, illo eligendi aliquid nisi atque aperiam eaque aliquam incidunt quod est nulla tempore, perferendis perspiciatis temporibus! Reprehenderit dignissimos nesciunt nisi ipsam. Modi quidem non asperiores cupiditate autem necessitatibus voluptatibus, ad itaque perspiciatis distinctio rerum vel fuga commodi eos! Nam quis facilis similique maxime, mollitia doloremque eos omnis maiores quae illo cumque nobis cupiditate atque, numquam, aspernatur nulla excepturi laboriosam enim quia itaque! Culpa ipsam aperiam at, nihil ipsum quis eligendi fugiat, nobis officia maiores perferendis praesentium nesciunt vero. Et ea similique ipsum quae repellendus tempora, eius nihil iste impedit porro assumenda consequuntur! Eos, quis eveniet libero ab officia aperiam consequuntur ratione similique sunt corrupti magnam repellendus nobis. Rem neque, totam ea quo beatae non accusamus incidunt maiores harum iure! Pariatur deleniti saepe, consequatur neque possimus odio facilis officia autem laborum veritatis facere ipsa assumenda ipsum, ullam sequi officiis error omnis eaque culpa architecto maiores repellendus? Commodi iure quo ex? Dolorum ipsam, atque blanditiis autem eaque ab praesentium alias est consequatur, eligendi porro debitis vero nulla. Dolorum incidunt laudantium minima culpa quas dolores voluptatem dicta distinctio temporibus facere, excepturi, perferendis, nisi repellendus qui? Eveniet voluptas consectetur maiores consequuntur quasi minima modi magnam officia, recusandae libero vel nulla eum natus molestias, ex suscipit beatae eius labore! Fugiat laborum ut voluptates praesentium quisquam, reiciendis sint magni eligendi odit eveniet ratione pariatur rerum quibusdam qui ipsam veritatis eius corrupti provident asperiores. Voluptatum totam dolore delectus quisquam repellat porro? Dignissimos, totam delectus blanditiis excepturi recusandae voluptatibus repellat consequuntur corrupti consectetur a hic.
                    </p>
                </div>
        </motion.div>
    )
}

export default InitialAbout